// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGAkBkwYq0TVbyIcUemMr7cq3fm9uVt4o',
    appId: '1:648753736679:web:e8da2e7b0f45f1f36a6b42',
    messagingSenderId: '648753736679',
    projectId: 'scholar-chat-7433a',
    authDomain: 'scholar-chat-7433a.firebaseapp.com',
    storageBucket: 'scholar-chat-7433a.firebasestorage.app',
    measurementId: 'G-ER7HQ3F7R5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByVByMfKbjjVkAnSLNM_IwROeyU7j2_0w',
    appId: '1:648753736679:android:d3b81efa81f247f66a6b42',
    messagingSenderId: '648753736679',
    projectId: 'scholar-chat-7433a',
    storageBucket: 'scholar-chat-7433a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr_icWkMxN7gek35TCNH0BrHfUC6NInIo',
    appId: '1:648753736679:ios:86a9dd39f602e9ad6a6b42',
    messagingSenderId: '648753736679',
    projectId: 'scholar-chat-7433a',
    storageBucket: 'scholar-chat-7433a.firebasestorage.app',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr_icWkMxN7gek35TCNH0BrHfUC6NInIo',
    appId: '1:648753736679:ios:86a9dd39f602e9ad6a6b42',
    messagingSenderId: '648753736679',
    projectId: 'scholar-chat-7433a',
    storageBucket: 'scholar-chat-7433a.firebasestorage.app',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGAkBkwYq0TVbyIcUemMr7cq3fm9uVt4o',
    appId: '1:648753736679:web:12f8cc29b92040576a6b42',
    messagingSenderId: '648753736679',
    projectId: 'scholar-chat-7433a',
    authDomain: 'scholar-chat-7433a.firebaseapp.com',
    storageBucket: 'scholar-chat-7433a.firebasestorage.app',
    measurementId: 'G-X5GEFCJK5F',
  );
}
